// r_matrix_analysis.js — `runMatrixAnalysis()` + `buildNetwork()` for every WebR surface.
//
// GENERATED by authoring_v2/gen_r_matrix_analysis.py. DO NOT EDIT BY HAND — regenerate:
//     python3 authoring_v2/gen_r_matrix_analysis.py
// The generator extracts the functions verbatim from phylochemistry.R and applies a small
// named patch set (Rfast/shipunov/Shiny have no WebAssembly path). It FAILS rather than
// emitting a wrong shim if the course source moves under a patch, so a stale copy cannot
// ship silently. `tests/r_matrix_analysis.test.mjs` runs it in --check mode.
//
// buildNetwork() (book ch.7) rides along unpatched — see the note above its definition.
// Verified working in a real headless browser on 2026-09-22 by tests/matrix_analysis_smoke.mjs
// (weighted igraph layout, bare two-column fallback, directed, and reciprocal collapse).
//
// Shipped as a JS string and evaluated by webr-console.js, the same shape as webr_view.js's
// VIEW_R_SHIM — it is eval'd BEFORE webr_reset.js's RESET_R_SHIM, so `reset session` keeps it.
//
// Source of truth: phylochemistry/phylochemistry.R lines 14188-15039 (sha256 e8d77fdb9326).

export const MATRIX_ANALYSIS_R_SHIM = `## runMatrixAnalysis — the CHEM 5725 analysis verb, ported for WebR.
## GENERATED by authoring_v2/gen_r_matrix_analysis.py — DO NOT EDIT THIS FILE BY HAND.
## Source: phylochemistry/phylochemistry.R lines 14188-15039 (sha256 e8d77fdb9326).
## Patches applied (why each one exists is documented in the generator):
##   - Rfast::Dist -> stats::dist (sampling loop) — Rfast has no wasm binary
##   - Rfast::Dist -> stats::dist (final pass) — Rfast has no wasm binary
##   - shipunov::Bclust -> vendored .rma_Bclust — shipunov has no wasm build anywhere
##   - Rtsne -> Rtsne::Rtsne — the shim attaches nothing globally
##   - fpc::dbscan -> dbscan::dbscan — fpc hard-imports mclust, which has no wasm build
##   - umap -> teachable stop() — umap imports reticulate, which needs a Python WebR has not got
##   - findClusterParameters (a Shiny app) -> teachable stop(), dbscan branch
##   - ips::descendants -> vendored .rma_descendants — ips imports XML, which has no wasm build
##   - findClusterParameters (a Shiny app) -> teachable stop(), kmeans branch

## ── vendored: shipunov 1.17.1 Bclust + Hcl2mat (Alexey Shipunov, GPL >= 2) ──────────────────────
## shipunov has no WebAssembly build. These two functions are pure base R and are the ONLY thing
## runMatrixAnalysis() needs from it (bootstrap support values on the hclust tree), so they are
## carried here verbatim rather than reimplemented — the numbers must match what the book prints.
## ONE line differs from upstream: parallel::mclapply -> lapply, flagged where it happens.
.rma_Hcl2mat <- function(hcl) {
 nr <- as.integer(nrow(hcl$merge))
 m <- matrix(0L, nrow=nr, ncol=nr+1L)
 for (i in seq_len(nr)) {
  left <- hcl$merge[i, 1L]
  if (left < 0L) {
  m[i, -left] <- 1L # negative values are observations
  } else {
  m[i, ] <- m[left, ] # positive values are child clusters
  }
 right <- hcl$merge[i, 2L]
 if (right < 0L) {
  m[i, -right] <- 1L
  } else {
  m[i, ] <- m[i,] | m[right, ]
  }
 }
return(m)
}

.rma_Bclust <- function(data, method.d="euclidean", method.c="ward.D",
 FUN=function(.x) hclust(dist(.x, method=method.d), method=method.c),
 iter=1000, mc.cores=1, monitor=TRUE, bootstrap=TRUE, relative=FALSE,
 hclist=NULL) {
 .calc.matches <- function(origin, current, nc=ncol(origin)) {
  one <- tcrossprod(origin, current) # both 1
  zero <- tcrossprod(1 - origin, 1 - current) # both 0
  res <- rowSums(one + zero == nc) # absolute matches (cluster present or absent)
  zeros <- sum(res == 0) # how many non-matches
  if (zeros > 0 && relative) { # select non-matches and calculate _relative matches_
  dsts <- as.matrix(dist(rbind(origin[res == 0, ], current), # find distances
   method="binary"))[seq_len(zeros), -seq_len(zeros), drop=FALSE] # asymmetric binary
  res[res == 0] <- apply(dsts, 1, min) # replace zeroes with closest distances
  }
  res
 }
 fun <- match.fun(FUN)
 if (is.null(hclist)) hcl <- fun(data) else hcl <- hclist[[1]]
 origin <- .rma_Hcl2mat(hcl)
 if (!bootstrap) iter <- ncol(data) # jacknife
 if (!is.null(hclist)) iter <- length(hclist) - 1 # pre-built list
 ## WebR has no \`parallel\`: the base package is present but its shared object does not load
 ## ("could not load dynamic lib: .../parallel/libs/parallel.so"), and there is no fork support in a
 ## browser anyway. phylochemistry always calls Bclust with the default mc.cores=1, for which
 ## mclapply IS lapply, so this is the same computation and not an approximation.
 v <- lapply(seq_len(iter), function(.y, origin, size, fun, nco) {
  if (!is.null(hclist)) {
   current <- .rma_Hcl2mat(hclist[[.y + 1]]) # pre-built list
  } else {
  if(!bootstrap) {
   current <- .rma_Hcl2mat(fun(data[, -.y])) # jacknife
  } else {
   current <- .rma_Hcl2mat(fun(data[, sample.int(ncol(data), replace=TRUE)]))
  }}
  if (monitor) cat(".")
  return(list(matches=.calc.matches(origin, current, nco), current=current))
  },
 origin=origin, size=ncol(data), fun=fun, nco=ncol(origin))
 if (monitor) cat("\\n")
 values <- colSums(do.call(rbind, lapply(v, \`[[\`, "matches")))/iter
 con <- t(Reduce("+", lapply(v, \`[[\`, "current")))/iter
 if (is.null(hclist)) row.names(con) <- row.names(data) else row.names(con) <- hcl$labels
 b.meth <- ifelse(bootstrap, "Bootstrap", "Jackknife")
 b.clust <- list(values=values, hclust=hcl, consensus=con, meth=b.meth, iter=iter)
 class(b.clust) <- "Bclust"
 b.clust
}

## ── vendored: ips 0.1.1 descendants() (C. Heibl, GPL-3) ───────────────────────────────────
## ips itself is unusable in WebR: it has a wasm binary, so it INSTALLS, but its namespace imports
## XML, which has no wasm build anywhere, so the first ips:: call dies. runMatrixAnalysis needs one
## function from it — the tip numbers below an internal node, for annotating a clade whose members
## all share a property. Pure base R, so it travels.
.rma_descendants <- function(phy, node, type = "t", ignore.tip = TRUE, labels = FALSE) {
  if (inherits(phy, "phylo")) {
    edge <- phy$edge
  } else {
    if (!is.matrix(phy)) {
      stop("'phy' must be of classes 'phylo' or 'matrix'")
    } else {
      edge <- phy
      labels <- FALSE
    }
  }
  if (length(node) > 1) stop("'node' must be vector of length 1")
  type <- match.arg(type, c("all", "daughter", "internal", "terminal"))
  tips <- setdiff(edge[, 2], edge[, 1])
  if (node <= max(tips)) {
    if (ignore.tip) {
      x <- node
    } else {
      stop("node ", node, " is not an internal node")
    }
  } else {
    x <- edge[edge[, 1] == node, 2] # immediate daughter nodes
    if (type %in% c("internal", "terminal", "all")) {
      repeat {
        xx <- x
        x <- sort(unique(c(x, edge[, 2][edge[, 1] %in% x])))
        if (identical(x, xx)) break
      }
      if (type == "internal") x <- setdiff(x, tips)
    }
  }
  if (type == "terminal") {
    x <- intersect(x, tips)
    if (labels) x <- phy$tip.label[x]
  }
  x
}

runMatrixAnalysis <-    function(
                            data,
                            analysis = c(
                                "pca", "pca_ord", "pca_dim",
                                "mca", "mca_ord", "mca_dim",
                                "mds", "mds_ord", "mds_dim",
                                "tsne", "dbscan", "kmeans",
                                "hclust", "hclust_phylo", "hclust_cat", "dist"
                            ),
                            parameters = NULL,
                            column_w_names_of_multiple_analytes = NULL,
                            column_w_values_for_multiple_analytes = NULL,
                            columns_w_values_for_single_analyte = NULL,
                            columns_w_additional_analyte_info = NULL,
                            columns_w_sample_ID_info = NULL,
                            transpose = FALSE,
                            distance_method = c("euclidean", "manhattan", "gower"),
                            agglomeration_method = c(
                                "ward.D2", "ward.D", "single", "complete",
                                "average", # (= UPGMA)
                                "mcquitty", # (= WPGMA)
                                "median", # (= WPGMC)
                                "centroid" # (= UPGMC)
                            ),
                            ## NOTE the order: "linkage_dendrogram" is FIRST and so is the
                            ## default. That is deliberate and differs from the retired
                            ## runMatrixAnalyses(), which defaulted to neighbour joining.
                            ## Every existing caller of runMatrixAnalysis -- the escape
                            ## rooms, the GC-MS functions, the book -- was written against
                            ## the linkage/Bclust behaviour this function has always had,
                            ## so defaulting to NJ would have silently changed trees that
                            ## puzzles already grade against. Nothing live relied on the
                            ## plural's NJ default (its hclust callers all passed
                            ## tree_method explicitly).
                            tree_method = c(
                                "linkage_dendrogram", # hclust -> as.phylo; honours agglomeration_method; bootstrapped
                                "neighbor_joining"    # ape::nj; additive, non-ultrametric; IGNORES agglomeration_method
                            ),
                            unknown_sample_ID_info = NULL,
                            components_to_return = 2,
                            scale_variance = NULL, ## default = TRUE, except for hclust, then default = FALSE
                            na_replacement = c("mean", "none", "zero", "drop"),
                            output_format = c("wide", "long"),
                            ...
                        ) {

    # Check that argument names are spelled correctly

        passed_args <- names(c(as.list(environment()), list(...)))

        if (!all(passed_args %in%
            c(
                "data",
                "analysis",
                "parameters",
                "column_w_names_of_multiple_analytes",
                "column_w_values_for_multiple_analytes",
                "columns_w_values_for_single_analyte",
                "columns_w_additional_analyte_info",
                "columns_w_sample_ID_info",
                "transpose",
                "distance_method",
                "agglomeration_method",
                "tree_method",
                "unknown_sample_ID_info",
                "components_to_return",
                "scale_variance",
                "na_replacement",
                "output_format",
                "..."
            ))
        ) {stop("One of your argument names is misspelled, please double check spelling.")}

    # Check that column names are spelled correctly

        if( any(
            !c(
                column_w_names_of_multiple_analytes,
                column_w_values_for_multiple_analytes,
                columns_w_values_for_single_analyte,
                columns_w_additional_analyte_info,
                columns_w_sample_ID_info
            ) %in% colnames(data)
            ) == TRUE
        ) {
            stop("There is a mismatch in the column names delivered to the command and the column names in your data. Please double check the spelling of your column names you gave to the command.")
        }

        if (all(c(
            is.null(column_w_values_for_multiple_analytes),
            is.null(columns_w_values_for_single_analyte)
        ))) { stop("You need to specify at least one column with values for analytes.")}

    # Pre-process data

        # Add analyte_unique_ID_column if necessary

            # if( length(columns_for_analyte_unique_ID) > 1 ) {
                #add analyte_unique_ID column if necessary
            # }

        # Remove columns that are not included in input column lists

            if (length(
                    which(!colnames(data) %in% 
                        c(
                            column_w_names_of_multiple_analytes,
                            column_w_values_for_multiple_analytes,
                            columns_w_values_for_single_analyte,
                            columns_w_additional_analyte_info,
                            columns_w_sample_ID_info
                        )
                    )
                ) > 0 
            ) {
                data <- data[,-which(!colnames(data) %in% 
                    c(
                        column_w_names_of_multiple_analytes,
                        column_w_values_for_multiple_analytes,
                        columns_w_values_for_single_analyte,
                        columns_w_additional_analyte_info,
                        columns_w_sample_ID_info
                    )
                )]
            }

        # Check for duplicate analyte names

            if( length(columns_w_values_for_single_analyte) > 0 ) {
                if( any(duplicated(columns_w_values_for_single_analyte)) ) {
                    stop("There are duplicate analyte names in columns_w_values_for_single_analyte.")
                }
            }

            if( length(column_w_names_of_multiple_analytes) == 1 ) {
                n_unique_samples <- table(duplicated(data[,colnames(data) %in% columns_w_sample_ID_info]))[1]

                analyte_breakdown <- table(duplicated(data[,colnames(data) == column_w_names_of_multiple_analytes]))
                n_unique_groups_of_analytes <- sum(analyte_breakdown)/analyte_breakdown[1]

                if (n_unique_samples != n_unique_groups_of_analytes) {
                    stop("Either:\\n1. The variables you have specified in columns_w_sample_ID_info do not define groups of samples with unique sets of analytes and you probably need to add more variables to columns_w_sample_ID_info.\\n\\nOR\\n\\n2. Not all your samples have the same number of analytes in column_w_names_of_multiple_analytes/column_w_values_of_multiple_analytes. Please fix that before continuing.")
                }
            }

        # Remove analyte annotation columns before pivoting

            if( length(columns_w_additional_analyte_info) > 0 ) {
                analyte_annotation_free_data <- data[,-match(columns_w_additional_analyte_info, colnames(data))]
            } else {
                analyte_annotation_free_data <- data
            }

        # If no pivot required, skip pivoting

            if( length(column_w_names_of_multiple_analytes) == 0 & length(columns_w_values_for_single_analyte) >= 1 ) {
                data_wide <- analyte_annotation_free_data
                analyte_columns <- columns_w_values_for_single_analyte
                data_wide <- unique(data_wide)
            }

        # If pivoting required, pivot_wider any long-style data

            if( length(column_w_names_of_multiple_analytes) == 1 ) {
                data_wide <- pivot_wider(
                    analyte_annotation_free_data,
                    names_from = all_of(column_w_names_of_multiple_analytes),
                    values_from = all_of(column_w_values_for_multiple_analytes)
                )
                analyte_columns <- unlist(unique(analyte_annotation_free_data[,colnames(analyte_annotation_free_data) == column_w_names_of_multiple_analytes]))
                analyte_columns <- c(columns_w_values_for_single_analyte, analyte_columns)
            }

        # Check to see if analyte columns are numeric and compatible with analysis

            which_analyte_columns <- which(colnames(data_wide) %in% analyte_columns)
            are_they_numeric <- list()
            for( i in which_analyte_columns ) {
              are_they_numeric <- c(are_they_numeric, is.numeric(data_wide[[i]]))
            }

            # Should selected analysis proceed?

                if ( all(unlist(are_they_numeric)) ) {
                    if ( analysis %in% c("pca", "pca_dim", "pca_ord") ) {
                        # cat("Analytes are all numeric and compatible with the analysis selected.\\n")
                    }
                    if ( analysis %in% c("mca", "mca_ord", "mca_dim") ) {
                        stop("Analytes are all numeric, but the analysis selected is for categorical variables. Please choose a different analysis method.\\n")
                    }
                }

                if ( !all(unlist(are_they_numeric)) ) {
                    if (analysis %in% c("mca", "mca_ord", "mca_dim")) {
                        # cat("Analytes are all categorical and compatible with the analysis selected.\\n")
                    }
                    if ( analysis %in% c("pca", "pca_dim", "pca_ord") ) {
                        stop("Analytes are all categorical, but the analysis selected is for numeric variables. Please choose a different analysis method.\\n")
                    }

                }

        # Add sample_unique_ID_column if necessary, or just change column name of existing sample_unique_ID column

            if( length(columns_w_sample_ID_info) > 1 ) {
                sample_unique_IDs <- apply(
                    data_wide[,match(columns_w_sample_ID_info, colnames(data_wide))],
                    1, paste, collapse = "_"
                )
                if( any(duplicated(sample_unique_IDs)) ) {stop("columns_w_sample_ID_info specified do not lead to unique sample IDs")}
                data_wide$sample_unique_ID <- sample_unique_IDs
            } else {
                colnames(data_wide)[colnames(data_wide) == columns_w_sample_ID_info] <- "sample_unique_ID"
                if( any(duplicated(data_wide$sample_unique_ID)) ) {stop("columns_w_sample_ID_info specified do not lead to unique sample IDs")}
            }

            # Make sure "sample_unique_ID" is character
                data_wide$sample_unique_ID <- as.character(data_wide$sample_unique_ID)

        # Prepare the matrix

            matrix <- as.data.frame(data_wide[,match(analyte_columns, colnames(data_wide))])
            rownames(matrix) <- data_wide$sample_unique_ID

        # Handle NAs

            if( na_replacement[1] == "none") {
            }

            if( na_replacement[1] == "drop" ) {
                message("Dropping any variables in your dataset that have NA as a value.\\nVariables dropped:\\n")
                if (length(names(which(apply(is.na(matrix), 2, any)))) > 0) {
                    message(names(which(apply(is.na(matrix), 2, any))))    
                } else {
                    message("none")
                }
                cat("\\n")
                matrix <- matrix[,!apply(is.na(matrix), 2, any)]
            }
            if( na_replacement[1] %in% c("zero", "mean") ) {

                if( any(is.na(matrix)) ) {
                    
                    message(paste0("Replacing NAs in your data with ", na_replacement[1]), "\\n")

                        for( column in 1:dim(matrix)[2]) {
                            
                            if( any(is.na(matrix[,column])) ) {

                                if( na_replacement[1] == "mean" ) {
                                    replacement <- mean(matrix[,column], na.rm = TRUE)
                                }
                                if( na_replacement[1] == "zero" ) {
                                    replacement <- 0
                                }
                                if( !any(na_replacement %in% c("mean", "zero")) ) {
                                    stop("Your data contains NAs. Please specify how to deal with them using na_replacement. \\n")
                                }
                                
                                matrix[,column][is.na(matrix[,column])] <- as.numeric(replacement)

                            } else {}
                        }
                }
            }

        # Transpose matrix, if requested
            if( transpose == TRUE ) { matrix <- t(matrix) }

        # Run unknown, if requested

            if( length(unknown_sample_ID_info) > 0 ) {
            
                ## Use na_replacement != "drop"

                    if( na_replacement[1] != "drop" ) {
                      stop("It is highly recommended that you use na_replacement = \\"drop\\" when matching an unknown, since anything with an NA value will be sent to the bottom of the matching list.")
                    }

                ## Separate unknown and knowns matrix

                    sample_ID_of_unknown <- unknown_sample_ID_info
                    index_of_unknown <- which(rownames(matrix) == sample_ID_of_unknown)
                    unknown <- matrix[index_of_unknown,]
                    matrix_minus_unknown <- matrix[-c(index_of_unknown),]

                ## Identify how many knowns there are to test

                    indices_to_test <- seq(1, dim(matrix_minus_unknown)[1], 1)

                ## Loop and select 20 nearest neighbors until there are just 100 left

                    while( length(indices_to_test) > 100 ) { ## Has been optimized for 50, 100, and 1000 indeces bites. 100 and 1000 both take ~5s.

                        ## Select 100 entries at random, subset matrix_minus_unknown for that, append the unknowns
                        
                            indices_being_tested <- sample(indices_to_test, 100, replace = FALSE)

                            matrix_to_be_tested <- matrix_minus_unknown[indices_being_tested,]
                            matrix_to_be_tested <- rbind(unknown, matrix_to_be_tested)
                            dist <- as.matrix(stats::dist(matrix_to_be_tested))
                            results <- data.frame(
                              distance = dist[2:dim(dist)[1], 1],
                              index = indices_being_tested
                            )

                        ## Keep closest 20 indices, modify indices_to_test

                            indices_to_keep <- results[order(results$distance),]$index[1:20]
                            indices_to_toss <- indices_being_tested[!indices_being_tested %in% indices_to_keep]
                            indices_to_test <- indices_to_test[!indices_to_test %in% indices_to_toss]

                    }

                    ## Test the last 100 neighbors and return the closest 10

                        final_matrix_to_be_tested <- rbind(unknown, matrix_minus_unknown[indices_to_test,])
                        dist <- as.matrix(stats::dist(final_matrix_to_be_tested))
                        results <- data.frame(
                          distance = dist[2:dim(dist)[1], 1],
                          index = indices_to_test
                    )

                    if( length(indices_to_test) < 10 ) {
                        number_for_final_tree <- length(indices_to_test)
                    } else {
                        number_for_final_tree <- 10
                    }

                    indices_to_keep <- results[order(results$distance),]$index[1:number_for_final_tree]
                    indices_to_keep

                ## Subset the matrix

                    matrix <- rbind(unknown, matrix_minus_unknown[indices_to_keep,])

                    ### THINK CAREFULLY HERE! THINGS SOMEWHAT CLOSE TO THE UNKNOWN 
                    ### MIGHT NOT CLUSTER DIRECTLY WITH IT
                    ### DEPENDING ON HOW RELATED THEY ARE TO OTHER THINGS

            }

    # Run the matrix analysis selected

        # Scale data, unless not requested

            if ( is.null(scale_variance) ) {
                if (analysis != "hclust") {scale_variance <- TRUE} else {scale_variance <- FALSE}
            }

            if( scale_variance == TRUE & !analysis %in% c("mca", "mca_ord", "mca_dim")) {
                
                scaled_matrix <- scale(matrix)

                if( any(is.na(scaled_matrix)) ) {
                    message("Some analytes have zero variance and will be assigned a value of zero in the scaled matrix.")
                    scaled_matrix[is.na(scaled_matrix)] <- 0
                }

            }

            if( scale_variance == FALSE ) {
                scaled_matrix <- matrix
            }

        ## HCLUST, HCLUST_PHYLO ##

            if( analysis == "hclust" | analysis == "hclust_phylo") {

                ## Two ways to turn the data into a tree. \`linkage_dendrogram\` is
                ## hierarchical clustering proper -- the step-by-step merging the book
                ## teaches -- and it is the only one that honours agglomeration_method
                ## and that yields bootstrap support. \`neighbor_joining\` is the
                ## phylogenetic method; it works from the distance matrix alone and
                ## IGNORES agglomeration_method entirely.
                if (tree_method[1] == "linkage_dendrogram") {

                    ## BClust approach to bootstrapped hclust

                        bclust <- .rma_Bclust(
                            scaled_matrix, method.d = distance_method[1],
                            method.c = agglomeration_method[1],
                            monitor = FALSE
                        )
                        phylo <- ape::as.phylo(bclust$hclust)

                } else if (tree_method[1] == "neighbor_joining") {

                    ## The distance matrix is computed further down for the other
                    ## analyses, so neighbour joining makes its own here.
                    if (distance_method[1] == "gower") {
                        nj_dist_matrix <- cluster::daisy(scaled_matrix, metric = "gower")
                    } else {
                        nj_dist_matrix <- stats::dist(scaled_matrix, method = distance_method[1])
                    }
                    phylo <- ape::nj(nj_dist_matrix)

                } else {
                    stop("tree_method must be one of \\"neighbor_joining\\" or \\"linkage_dendrogram\\".")
                }

                if( analysis == "hclust_phylo" ) {
                    return(phylo)
                    stop("Returning hclust_phylo.")
                }
                clustering <- ggtree::fortify(phylo)
                clustering$sample_unique_ID <- clustering$label
                clustering$bootstrap <- NA

                ## Add bootstrap values starting from the furthest node to the highest
                ## node. Only the linkage route has them -- neighbour joining is not
                ## bootstrapped here, so its bootstrap column stays NA.
                if (tree_method[1] == "linkage_dendrogram") {
                    bs_vals <- data.frame(
                        xval = clustering$x[clustering$isTip != TRUE],
                        bs_val = NA
                    )
                    for (i in 1:length(bclust$value)) { # i=1
                        bs_vals$bs_val[
                            order(bs_vals$xval, decreasing = TRUE)[i]
                        ] <- bclust$values[i]
                    }
                    clustering$bootstrap[clustering$isTip != TRUE] <- bs_vals$bs_val
                }

                ## CUTTING THE TREE (2026-09-23). \`parameters\` cuts the dendrogram
                ## into groups and returns them as a \`cluster\` column, deliberately the
                ## SAME shape k-means already returns -- one column, values "cluster_1",
                ## "cluster_2", ... -- so that chapters 8 and 10 rhyme instead of
                ## diverging. Without it there is no course-native way to cut a tree at
                ## all: the hclust branch returns ggtree coordinates, not an hclust
                ## object, so stats::cutree() on the output fails with "invalid 'tree'
                ## ('merge' component)" and the student has to drop to base R -- which
                ## is exactly the move the book tells them not to make.
                ##
                ## TWO WAYS TO ASK, because they are different questions:
                ##   parameters = c(4)            -- cut into 4 groups (k)
                ##   parameters = c(k = 4)        -- the same, said explicitly
                ##   parameters = c(height = 5)   -- cut ACROSS the tree at height 5,
                ##                                   and however many groups that
                ##                                   leaves is the answer
                ## The height form is the one the canyon scenario's flood-gate escape
                ## re-poses on the world (water level = cut height), and it is the only
                ## form that can answer "how many groups are there at this height" --
                ## with k the count is an input, so "there is no fourth group" cannot
                ## be expressed. Bare/\`k =\` is kept as the default because k-means
                ## already reads a bare number that way.
                ##
                ## Internal nodes get NA, like \`bootstrap\` does for tips: only tips are
                ## samples, and only samples belong to a group.
                if ( length(parameters) > 0 ) {

                    if (tree_method[1] != "linkage_dendrogram") {
                        stop(paste0(
                            "Cutting a tree into groups needs tree_method = ",
                            "\\"linkage_dendrogram\\". Neighbour joining does not build ",
                            "the tree by merging groups, so there are no merge heights ",
                            "to cut at."
                        ))
                    }

                    param_name <- names(parameters)[1]
                    if (is.null(param_name)) { param_name <- "" }
                    if (is.na(param_name)) { param_name <- "" }

                    if (param_name %in% c("h", "height")) {

                        cut_height <- as.numeric(parameters[1])
                        if (is.na(cut_height) || cut_height <= 0) {
                            stop("parameters = c(height = ...) needs a positive height to cut the tree at.")
                        }
                        cut_groups <- stats::cutree(bclust$hclust, h = cut_height)

                    } else if (param_name %in% c("", "k")) {

                        n_groups <- as.integer(parameters[1])
                        if (is.na(n_groups) || n_groups < 1) {
                            stop("parameters must be the number of groups to cut the tree into, e.g. parameters = c(3), or a height, e.g. parameters = c(height = 5).")
                        }
                        if (n_groups > nrow(scaled_matrix)) {
                            stop(paste0(
                                "Cannot cut ", nrow(scaled_matrix), " samples into ",
                                n_groups, " groups."
                            ))
                        }
                        cut_groups <- stats::cutree(bclust$hclust, k = n_groups)

                    } else {
                        stop(paste0(
                            "parameters was named \\"", param_name, "\\". For a tree it must be ",
                            "either a number of groups -- parameters = c(3) or c(k = 3) -- ",
                            "or a height to cut at -- parameters = c(height = 5)."
                        ))
                    }

                    clustering$cluster <- NA_character_
                    hit <- match(clustering$label, names(cut_groups))
                    clustering$cluster[!is.na(hit)] <-
                        paste0("cluster_", cut_groups[hit[!is.na(hit)]])
                }
            }

            if (analysis == "hclust_cat") {

                ## "bootstrap" approach
                    temp <- as.data.frame(lapply(scaled_matrix, function(x) if(is.character(x)) factor(x) else x))
                    rownames(temp) <- rownames(scaled_matrix)
                    scaled_matrix <- temp
                    createHclustObject <- function(x)hclust(cluster::daisy(x, metric = distance_method[1]), method = agglomeration_method[1])
                    b <- bootstrap(scaled_matrix, fun = createHclustObject, n = 100L)
                    phylo <- ape::as.phylo(createHclustObject(scaled_matrix))

                    clustering <- ggtree::fortify(phylo)
                    clustering$sample_unique_ID <- clustering$label
                    clustering$bootstrap <- NA

                ## Add bootstrap values starting from the furthest node to the highest node
                    bs_vals <- data.frame( xval = clustering$x[clustering$isTip != TRUE], bs_val = NA )
                    for (i in 1:length(b)) { bs_vals$bs_val[order(bs_vals$xval, decreasing = TRUE)[i]] <- b[i] }

                clustering$bootstrap[clustering$isTip != TRUE] <- bs_vals$bs_val

            }

            # if( analysis == "hclust" | analysis == "hclust_phylo" ) {
            #     scaled_matrix <- as.data.frame(lapply(scaled_matrix, function(x) if(is.character(x)) factor(x) else x))
            #     createHclustObject <- function(x)hclust(cluster::daisy(x, metric = distance_method[1]), method = agglomeration_method[1])
            #     b <- bootstrap(scaled_matrix, fun = createHclustObject, n = 100L)
            #     phylo <- ape::as.phylo(createHclustObject(scaled_matrix))
            #     if( analysis == "hclust_phylo" ) {
            #         return(phylo)
            #         stop("Returning hclust_phylo.")
            #     }
            #     clustering <- ggtree::fortify(phylo)
            #     clustering$sample_unique_ID <- clustering$label
            #     clustering$bootstrap <- NA

            #     ## Add bootstrap values starting from the furthest node to the highest node
            #         bs_vals <- data.frame(
            #             xval = clustering$x[clustering$isTip != TRUE],
            #             bs_val = NA
            #         )
            #         for (i in 1:length(b)) { # i=1
            #             bs_vals$bs_val[
            #                 order(bs_vals$xval, decreasing = TRUE)[i]
            #             ] <- b[i]
            #         }

            #     clustering$bootstrap[clustering$isTip != TRUE] <- bs_vals$bs_val
            # }

        # Generate distance matrix

            if(  !analysis %in% c("mca", "mca_ord", "mca_dim") ) {

                ## \`gower\` is in distance_method's list and stats::dist cannot compute
                ## it -- it needs cluster::daisy. Without this branch, asking for gower
                ## silently gave you a euclidean distance instead.
                if (distance_method[1] == "gower") {
                    dist_matrix <- cluster::daisy(scaled_matrix, metric = "gower")
                } else {
                    dist_matrix <- stats::dist(scaled_matrix, method = distance_method[1])
                }

                if( analysis == "dist") {

                    ## Two shapes, chosen with output_format. The default "wide" gives
                    ## the \`dist\` object base R expects (hclust(), cmdscale(), print()).
                    ## "long" gives one row per PAIR -- sample_1, sample_2, distance,
                    ## plus the sample ID columns suffixed for each side -- which is the
                    ## shape an edge list wants, and what the networks chapter plots.
                    if( output_format[1] == "long" ) {
                        df <- as.data.frame(as.table(as.matrix(dist_matrix)))
                        names(df) <- c("sample_1", "sample_2", "distance")
                        df <- filter(df, distance != 0)
                        clustering <- df

                        ## WITH A SINGLE columns_w_sample_ID_info, THAT COLUMN NO LONGER EXISTS.
                        ## The pre-processing above (~line 14316) RENAMES a lone ID column to
                        ## "sample_unique_ID" rather than adding one, so asking for
                        ## c("lake", "sample_unique_ID") matched NA and the subset blew up with an
                        ## error naming neither the argument nor the reason. Two or more ID columns
                        ## survive as themselves and a new sample_unique_ID is pasted together, which
                        ## is why the 2-column call worked and the 1-column call did not (found in
                        ## WebR, 2026-09-23). Take only the ID columns that actually survived.
                        dist_id_cols <- unique(c(
                            intersect(columns_w_sample_ID_info, colnames(data_wide)),
                            "sample_unique_ID"
                        ))
                        dist_id_frame <- data_wide[, match(dist_id_cols, colnames(data_wide)), drop = FALSE]

                        clustering <- right_join(
                          dist_id_frame, clustering,
                          by = c("sample_unique_ID" = "sample_1"), suffix = c("_sample_1", "_sample_2")
                        )

                        clustering <- right_join(
                          dist_id_frame, clustering,
                          by = c("sample_unique_ID" = "sample_2"), suffix = c("_sample_1", "_sample_2")
                        )

                        colnames(clustering)[colnames(clustering) == "sample_unique_ID"] <- "sample_unique_ID_sample_1"
                        clustering <- select(clustering, sample_unique_ID_sample_1, sample_unique_ID_sample_2, distance, everything())
                        return(clustering)
                    }

                    return(dist_matrix)
                }

            }

            if( analysis %in% c("mca", "mca_ord", "mca_dim") ) { scaled_matrix <- matrix }

        ## Dimensionality reduction

            ## MDS

                if( analysis == "mds" ) {
                    coords <- stats::cmdscale(dist_matrix)
                    colnames(coords) <- c("Dim_1", "Dim_2")
                    clustering <- as_tibble(coords)
                    clustering$sample_unique_ID <- rownames(coords)
                }
        
            ## tSNE

                if( analysis == "tsne" ) {
                    clustering <- Rtsne::Rtsne(scaled_matrix, theta = 0.0, perplexity = 2)
                    clustering <- as.data.frame(clustering$Y)
                    clustering$sample_unique_ID <- rownames(scaled_matrix)
                    colnames(clustering) <- c("Dim_1", "Dim_2", "sample_unique_ID")
                    clustering <- select(clustering, sample_unique_ID, Dim_1, Dim_2)
                    rownames(clustering) <- NULL
                }

            ## umap

                if( analysis == "umap" ) {
                    stop("umap cannot run in the browser: the umap package needs reticulate and a Python runtime. Use analysis = \\"tsne\\", \\"mds\\" or \\"pca\\" here.")
                    clustering$sample_unique_ID <- rownames(clustering)
                    colnames(clustering) <- c("Dim_1", "Dim_2", "sample_unique_ID")
                    clustering <- select(clustering, sample_unique_ID, Dim_1, Dim_2)
                    rownames(clustering) <- NULL
                }

            ## MCA, MCA_ORD, MCA_DIM ##

                if( analysis == "mca" ) {
                    message("Running Multiple Correspondence Analysis, extracting sample coordinates...\\n")
                    coords <- FactoMineR::MCA(matrix, graph = FALSE)$ind$coord[,c(1:components_to_return)]
                    clustering <- as_tibble(coords)
                    clustering$sample_unique_ID <- rownames(coords)
                    colnames(clustering) <- c("Dim_1", "Dim_2", "sample_unique_ID")
                    message("Done!\\n")
                }

                if( analysis == "mca_ord" ) {
                    message("Running Multiple Correspondence Analysis, extracting ordination plot...\\n")
                    coords <- FactoMineR::MCA(matrix, graph = FALSE)$var$eta2[,c(1,components_to_return)]
                    clustering <- as_tibble(coords)
                    clustering$analyte <- rownames(coords)
                    colnames(clustering) <- c("Dim_1", "Dim_2", "analyte")
                    clustering <- select(clustering, analyte, Dim_1, Dim_2)
                    return(clustering)
                    stop("Returning ordination plot coordinates. \\nDone!")
                }

                if( analysis == "mca_dim" ) {
                    message("Running Multiple Correspondence Analysis, extracting dimensional contributions...\\n")
                    coords <- FactoMineR::MCA(matrix, graph = FALSE)$eig[,2]
                    clustering <- tibble::enframe(coords, name = NULL)
                    clustering$principal_component <- names(coords)
                    clustering$principal_component <- as.numeric(gsub("dim ", "", clustering$principal_component))
                    colnames(clustering)[colnames(clustering) == "value"] <- "percent_variance_explained"
                    clustering <- select(clustering, principal_component, percent_variance_explained)
                    return(clustering)
                    stop("Returning eigenvalues. \\nDone!")
                }

            ## PCA, PCA_ORD, PCA_DIM ## 

                if( analysis == "pca" ) {
                    coords <- FactoMineR::PCA(scaled_matrix, graph = FALSE, scale.unit = FALSE)$ind$coord[,c(1:components_to_return)]
                    clustering <- as_tibble(coords)
                    clustering$sample_unique_ID <- rownames(coords)
                    # colnames(clustering) <- c("Dim_1", "Dim_2", "sample_unique_ID")
                }

                if( analysis == "pca_ord" ) {
                    coords <- FactoMineR::PCA(scaled_matrix, graph = FALSE, scale.unit = FALSE)$var$coord[,c(1:components_to_return)]
                    clustering <- as_tibble(coords)
                    clustering$analyte <- rownames(coords)
                    clustering <- select(clustering, analyte, c(paste0("Dim.", seq(1,components_to_return,1))))
                    # colnames(clustering) <- c("analyte", "Dim_1", "Dim_2")
                    return(clustering)
                    stop("Returning ordination plot coordinates.")
                }

                if( analysis == "pca_dim" ) {
                    coords <- FactoMineR::PCA(scaled_matrix, graph = FALSE, scale.unit = FALSE)$eig[,2]
                    clustering <- tibble::enframe(coords, name = NULL)
                    clustering$principal_component <- names(coords)
                    clustering$principal_component <- as.numeric(gsub("comp ", "", clustering$principal_component))
                    colnames(clustering)[colnames(clustering) == "value"] <- "percent_variance_explained"
                    clustering <- select(clustering, principal_component, percent_variance_explained)
                    return(clustering)
                    stop("Returning eigenvalues.")
                }
    
        ## Clustering

            if(  !analysis %in% c("mca", "mca_ord", "mca_dim") ) {

                if( any(is.na(scaled_matrix)) == TRUE ) {
                    stop("clustering cannot handle NA. Please choose an option for na_replacement.")
                }

            }

            ## DBSCAN

                if( analysis == "dbscan" ) {

                    if ( length(parameters) > 0 ) {
                        cluster_k <- parameters[1]
                        cluster_threshold <- parameters[2]
                    }

                    if ( length(parameters) == 0 ) {
                        stop("dbscan needs its parameters up front in the browser: runMatrixAnalysis(..., analysis = \\"dbscan\\", parameters = c(MinPts, eps)). The interactive picker (findClusterParameters) is a Shiny app and needs desktop R.")
                    }

                    message("Using", cluster_k, "as a value for k.\\n")
                    message("Using", cluster_threshold, "as a value for threshold.\\n")
                    clustering <- as_tibble(data.frame(
                        sample_unique_ID = colnames(as.matrix(dist_matrix)),
                        cluster = paste0("cluster_", dbscan::dbscan(dist_matrix, eps = as.numeric(cluster_threshold), minPts = as.numeric(cluster_k))$cluster)
                    ))
                    clustering$cluster[clustering$cluster == "cluster_0"] <- NA

                }

            ## k-means

                if (analysis == "kmeans") {

                    if ( length(parameters) > 0 ) {
                        n_clusters <- parameters[1]
                    }

                    if ( length(parameters) == 0 ) {
                        stop("kmeans needs its cluster count up front in the browser: runMatrixAnalysis(..., analysis = \\"kmeans\\", parameters = c(number_of_clusters)). The interactive picker (findClusterParameters) is a Shiny app and needs desktop R.")
                    }

                    message("Using", n_clusters, "as a value for cluster_number.\\n")
                    clustering <- as_tibble(data.frame(
                        sample_unique_ID = colnames(as.matrix(dist_matrix)),
                        cluster = stats::kmeans(x = matrix, centers = as.numeric(n_clusters), nstart = 25, iter.max = 1000)$cluster
                    ))

                }

            ## OPTICS

                # out <- dbscan::optics(scaled_matrix, minPts = 5)
                # out <- data.frame(
                #     order = out$order,
                #     reach_dist = out$reachdist,
                #     name = rownames(scaled_matrix)
                # )
                # out$name <- factor(out$name, levels = rev(rownames(scaled_matrix)[out$order]))
                # ggplot(out[2:19,]) +
                #     geom_col(aes(x = name, y = reach_dist))                                

    # If transpose = TRUE, then return without annotations

        if( transpose == TRUE ) {
            return(clustering)
            stop("Returning transposed cluster output. Make sure all your variables have the same units!")
        }
        
    # Post processing and return.

        if( !analysis %in% c("hclust_phylo")) {

            ## Add back annotations to the output

                ## The empty branch is LOAD-BEARING, not dead code. With exactly one
                ## columns_w_sample_ID_info the pre-processing above RENAMED that column to
                ## sample_unique_ID, so it is no longer in data_wide and there is nothing to
                ## join back -- the annotation is already there. Do not "tidy" this into an
                ## unconditional join: that is the same mistake the dist/long branch made
                ## (~line 14605), which threw an NA-subscript error naming neither the
                ## argument nor the reason. Regression test: test_runMatrixAnalysis_dist.R
                if( length(columns_w_sample_ID_info) == 1 ) {
                } else {
                clustering <-   right_join(
                                    data_wide[,match(
                                        c(columns_w_sample_ID_info, "sample_unique_ID"),
                                        colnames(data_wide))
                                    ], clustering, by = "sample_unique_ID"
                                )
                }

                rownames_matrix <- tibble::enframe(rownames(scaled_matrix), name = NULL)
                colnames(rownames_matrix)[1] <- "sample_unique_ID"

                # if (analysis != "pca") { ## Don't do this for pca for some reason?? I don't understand why...
                    clustering <- full_join(
                        clustering,
                        as_tibble(cbind(rownames_matrix, as_tibble(matrix))),
                        by = "sample_unique_ID"
                    )
                # }
                # clustering

                ## Order the returned matrix so that the sample_unique_ID comes first

                    clustering <- select(clustering, sample_unique_ID, everything())

            # Annotate internal nodes in tree output if all its descendants share a property

                if( analysis == "hclust" ) {
                    for( node in dplyr::filter(clustering, isTip == FALSE)$node ) {
                        for (sample_property in colnames(clustering)[colnames(clustering) %in% columns_w_sample_ID_info] ) {
                            descends <- clustering[clustering$node %in% .rma_descendants(phylo, node),]
                            if (length( unlist(unique(descends[,colnames(descends) == sample_property])) ) == 1 ) {
                                clustering[
                                    which(clustering$node == node),
                                    which(colnames(clustering) == sample_property)
                                ] <- unlist(descends[,colnames(descends) == sample_property])[1]
                            }
                        }
                    }
                }

            # Return results

                if( output_format[1] == "long" ) {
                    clustering <- pivot_longer(
                        clustering,
                        cols = c(which(colnames(clustering) == analyte_columns[1]): dim(clustering)[2]),
                        names_to = "analyte_name", 
                        values_to = "value"
                    )
                    analyte_annotation_frame <- unique(select(ungroup(data), all_of(c(column_w_names_of_multiple_analytes, columns_w_additional_analyte_info))))
                    clustering <- left_join(clustering, analyte_annotation_frame, by = c("analyte_name" = column_w_names_of_multiple_analytes))
                }

                return( clustering )
        }
}


## ── give the ported function its own lookup environment ────────────────────────────────────────
## The course source attaches dplyr/tidyr/tibble/ggplot2 with library(); the shim must not, or every
## room would silently inherit four attached packages it never asked for. Same lookups, no global
## masking. ggplot2 first -> dplyr last, so dplyr wins any shared name.
local({
  e <- new.env(parent = globalenv())
  for (p in c("ggplot2", "tibble", "tidyr", "dplyr")) {
    if (!requireNamespace(p, quietly = TRUE)) next
    ns <- asNamespace(p)
    for (nm in getNamespaceExports(p)) {
      v <- tryCatch(get(nm, envir = ns), error = function(e) NULL)
      if (!is.null(v)) assign(nm, v, envir = e)
    }
  }
  environment(runMatrixAnalysis) <<- e
})

## ── buildNetwork() — the book's chapter 7 verb, carried verbatim ───────────────────────────
## No patches: every external call is already namespace-qualified and the packages it needs
## (network, ggnetwork, igraph) are in ANALYSIS_PACKAGES. Unlike runMatrixAnalysis this one
## needs no enclosing environment — it uses base R only, plus collapseReciprocalEdges below,
## which it finds in globalenv() exactly as it does on the desktop.
## Source: phylochemistry/phylochemistry.R lines 11632-11700 and 11715-11860.
collapseReciprocalEdges <- function(edgelist, directed = NULL, tol = sqrt(.Machine$double.eps)) {

    n_input <- nrow(edgelist)
    edgelist <- edgelist[!duplicated(edgelist), , drop = FALSE]
    n_exact <- n_input - nrow(edgelist)
    if (n_exact > 0) {
        message("buildNetwork: dropped ", n_exact, " edge row(s) that were exact copies of another row.")
    }

    pair_key <- paste(
        pmin(edgelist[[1]], edgelist[[2]]),
        pmax(edgelist[[1]], edgelist[[2]]),
        sep = "\\r"
    )
    repeated <- duplicated(pair_key)
    if (isTRUE(directed) || !any(repeated)) {
        rownames(edgelist) <- NULL
        return(edgelist)
    }

    # For every row, does it match the first row sharing its pair key on all attributes?
    first_row <- match(pair_key, pair_key)
    agrees <- rep(TRUE, nrow(edgelist))
    if (ncol(edgelist) > 2) {
        for (i in 3:ncol(edgelist)) {
            x <- edgelist[[i]]
            if (is.numeric(x)) {
                ref <- x[first_row]
                same <- (is.na(x) & is.na(ref)) |
                    (!is.na(x) & !is.na(ref) & abs(x - ref) <= tol * pmax(1, abs(ref)))
            } else {
                x <- as.character(x)
                ref <- x[first_row]
                same <- (is.na(x) & is.na(ref)) | (!is.na(x) & !is.na(ref) & x == ref)
            }
            agrees <- agrees & same
        }
    }
    n_conflicting_pairs <- length(unique(pair_key[!agrees]))

    if (is.null(directed) && n_conflicting_pairs > 0) {
        message(
            "buildNetwork: ", n_conflicting_pairs, " node pair(s) appear more than once with ",
            "different edge attributes (e.g. A->B and B->A with different weights), so all ",
            nrow(edgelist), " edges were kept and the network is treated as directed. ",
            "Set directed = FALSE to keep one edge per pair (the first occurrence) instead."
        )
        rownames(edgelist) <- NULL
        return(edgelist)
    }

    collapsed <- edgelist[!repeated, , drop = FALSE]
    rownames(collapsed) <- NULL
    if (n_conflicting_pairs > 0) {
        message(
            "buildNetwork: directed = FALSE, so ", nrow(edgelist), " edges were collapsed to ",
            nrow(collapsed), ", one per node pair. ", n_conflicting_pairs, " pair(s) had ",
            "differing edge attributes; the first occurrence of each was kept."
        )
    } else {
        message(
            "buildNetwork: every repeated node pair (A->B and B->A) had matching edge ",
            "attributes, so the network is treated as undirected and ", nrow(edgelist),
            " edges were collapsed to ", nrow(collapsed), ". ",
            "Set directed = TRUE to keep both directions."
        )
    }
    collapsed
}

buildNetwork <- function(edgelist, node_attributes = NULL, facet_variable = NULL, directed = NULL) {

    edgelist <- as.data.frame(edgelist, stringsAsFactors = FALSE)
    if (ncol(edgelist) < 2) {
        stop("\`edgelist\` must have at least two columns: start node and end node.")
    }
    if (!is.null(directed) && !(isTRUE(directed) || isFALSE(directed))) {
        stop("\`directed\` must be NULL, TRUE or FALSE.")
    }

    edgelist[[1]] <- as.character(edgelist[[1]])
    edgelist[[2]] <- as.character(edgelist[[2]])

    edgelist <- collapseReciprocalEdges(edgelist, directed = directed)

    # Build from an explicit edgelist so row-level edge attributes are preserved.
    # multiple = TRUE: a same-direction repeat with differing attributes survives
    # collapseReciprocalEdges() and would otherwise make network() stop on parallel edges.
    network_object <- network::network(
        edgelist[, 1:2, drop = FALSE],
        matrix.type = "edgelist",
        ignore.eval = TRUE,
        multiple = TRUE
    )

    if (ncol(edgelist) > 2) {
        for (i in 3:ncol(edgelist)) {
            attr_name <- colnames(edgelist)[i]
            if (is.null(attr_name) || is.na(attr_name) || attr_name == "") {
                attr_name <- paste0("edge_attr_", i - 2)
            }
            network::set.edge.attribute(network_object, attr_name, edgelist[[i]])
        }
    }

    # Prefer a weighted force-directed layout when usable edge weights are present.
    layout_coords <- NULL
    if (ncol(edgelist) > 2 && requireNamespace("igraph", quietly = TRUE)) {
        weight_col <- c("edgeweight", "weight")
        weight_col <- weight_col[weight_col %in% colnames(edgelist)]
        if (length(weight_col) == 0) {
            weight_col <- colnames(edgelist)[3]
        } else {
            weight_col <- weight_col[1]
        }

        layout_weights <- suppressWarnings(as.numeric(edgelist[[weight_col]]))
        if (any(!is.na(layout_weights))) {
            min_pos <- suppressWarnings(min(layout_weights[layout_weights > 0], na.rm = TRUE))
            if (!is.finite(min_pos)) {
                min_pos <- 1e-06
            }
            layout_weights[is.na(layout_weights) | layout_weights <= 0] <- min_pos

            graph_for_layout <- igraph::graph_from_data_frame(
                data.frame(
                    from = edgelist[[1]],
                    to = edgelist[[2]],
                    weight = layout_weights,
                    stringsAsFactors = FALSE
                ),
                directed = FALSE
            )

            coords <- igraph::layout_with_fr(
                graph_for_layout,
                weights = igraph::E(graph_for_layout)$weight,
                niter = 2000
            )
            coords <- as.matrix(coords)
            rownames(coords) <- igraph::V(graph_for_layout)$name

            vertex_names <- network::get.vertex.attribute(network_object, "vertex.names")
            coords <- coords[match(vertex_names, rownames(coords)), , drop = FALSE]

            if (!any(is.na(coords))) {
                layout_coords <- coords
            }
        }
    }

    combined_network_frame <- ggnetwork::ggnetwork(
        network_object,
        arrow.gap = 0,
        layout = if (is.null(layout_coords)) "kamadakawai" else layout_coords,
        stringsAsFactors = FALSE
    )

    is_node <- (combined_network_frame$x == combined_network_frame$xend) &
        (combined_network_frame$y == combined_network_frame$yend)

    nodes <- combined_network_frame[is_node, c("x", "y", "vertex.names"), drop = FALSE]
    colnames(nodes)[3] <- "node_name"
    nodes <- nodes[!duplicated(nodes$node_name), , drop = FALSE]

    node_lookup <- nodes[, c("node_name", "x", "y"), drop = FALSE]
    colnames(node_lookup) <- c("node_name", "node_x", "node_y")

    edge_attributes <- NULL
    if (ncol(edgelist) > 2) {
        edge_attributes <- edgelist[, 3:ncol(edgelist), drop = FALSE]
    }

    edges <- data.frame(
        start_node = edgelist[[1]],
        end_node = edgelist[[2]],
        stringsAsFactors = FALSE
    )
    if (!is.null(edge_attributes)) {
        edges <- cbind(edges, edge_attributes)
    }

    start_idx <- match(edges$start_node, node_lookup$node_name)
    end_idx <- match(edges$end_node, node_lookup$node_name)

    edges$x <- node_lookup$node_x[start_idx]
    edges$y <- node_lookup$node_y[start_idx]
    edges$xend <- node_lookup$node_x[end_idx]
    edges$yend <- node_lookup$node_y[end_idx]

    if (any(is.na(edges$x) | is.na(edges$y) | is.na(edges$xend) | is.na(edges$yend))) {
        warning("Some edges could not be mapped to node coordinates; check edgelist node labels.")
    }

    edge_cols <- c("x", "y", "start_node", "xend", "yend", "end_node")
    extra_cols <- setdiff(colnames(edges), edge_cols)
    edges <- edges[, c(edge_cols, extra_cols), drop = FALSE]

    if (!is.null(node_attributes)) {
        node_attributes <- as.data.frame(node_attributes, stringsAsFactors = FALSE)
        node_key <- as.character(node_attributes[[1]])
        matched_attrs <- node_attributes[match(nodes$node_name, node_key), , drop = FALSE]

        # Avoid duplicating the node identifier column.
        if (ncol(matched_attrs) > 0) {
            matched_attrs <- matched_attrs[, -1, drop = FALSE]
        }
        nodes <- cbind(nodes, matched_attrs)
    }

    if (!is.null(facet_variable)) {
        warning("\`facet_variable\` is currently not implemented in buildNetwork().")
    }

    return(list(edges = edges, nodes = nodes))
}


## ── the retired runMatrixAnalyses() (plural), carried so old notes get a real message ──
runMatrixAnalyses <- function(...) {
    stop(
        "runMatrixAnalyses() (plural) was retired on 2026-09-22. Use runMatrixAnalysis() ",
        "(singular) instead \\u2014 it does everything the plural did and more.\\n\\n",
        "  - Wide data: the arguments are the same. Rename the function and it will run.\\n",
        "  - analysis = \\"dist\\": the singular returns a base R \`dist\` object by default. ",
        "For the long, one-row-per-pair data frame the plural returned, add ",
        "output_format = \\"long\\".\\n",
        "  - Hierarchical clustering: tree_method now defaults to \\"linkage_dendrogram\\" ",
        "rather than \\"neighbor_joining\\". Pass tree_method explicitly if you want NJ.\\n",
        call. = FALSE
    )
}

`;
