#!/usr/bin/env python3
"""
scenario_inventory.py — regenerate rooms/scenario_inventory.json.

WHY: scenarios each carry a codec `id` that MUST be unique (a collision makes two scenarios' submission
codes decode into each other). Agents kept colliding (e.g. two id-8 scenarios) because there was no
single place to see what exists. This scans every rooms/<chapter>/<scenario>/scenario.json plus the
`scenario_id`s reserved in decoder/decode_codes.R, and writes an inventory + the next free id.

Run from the escape_rooms/ dir (or anywhere): `python3 authoring/scenario_inventory.py`. Stdlib only.
Re-run after adding a scenario or changing an id. Read scenario_inventory.json BEFORE creating a new
scenario and take `next_free_id`.
"""
import json, re, glob, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # .../escape_rooms
OUT = ROOT / "rooms" / "scenario_inventory.json"
DECODER = ROOT / "decoder" / "decode_codes.R"


def main():
    scenarios, ids = [], {}
    for p in sorted(ROOT.glob("rooms/*/*/scenario.json")):
        try:
            d = json.loads(p.read_text())
        except Exception as e:
            print(f"WARN unreadable {p}: {e}"); continue
        rooms = d.get("rooms", [])
        built = [r for r in rooms if r.get("built")]
        phases = sorted({r.get("phase", "analysis") for r in rooms})
        # An escape exists in any of three forms: the legacy phase="escape" room, OR the current style —
        # a `lock` hotspot (the no-instructions keypad) in any room, OR a scenario-level `escapeDone`
        # screen. The phases-only check missed the current style (hawaii's valve-keypad escape, flagged
        # 2026-07-22), so detect all three.
        has_escape = (
            "escape" in phases
            or "escapeDone" in d
            or any(h.get("type") == "lock" for r in rooms for h in r.get("hotspots", []))
        )
        sid = d.get("id")
        rec = {
            "id": sid,
            "chapter": d.get("chapter"),
            "scenario": d.get("scenario"),
            "title": d.get("title"),
            "datasets": [ds.get("name") for ds in d.get("datasets", [])],
            "rooms_total": len(rooms),
            "rooms_built": len(built),
            "phases": phases,
            "has_escape": has_escape,
            "path": str(p.relative_to(ROOT)),
        }
        scenarios.append(rec)
        ids.setdefault(sid, []).append(rec["path"])

    # ids reserved in the decoder (incl. retired flat scenarios 1–5) — never reuse them
    reserved = sorted(set(int(m) for m in re.findall(r"scenario_id\s*=\s*(\d+)", DECODER.read_text())))
    dupes = {i: paths for i, paths in ids.items() if i is not None and len(paths) > 1}
    all_used = sorted(set([s["id"] for s in scenarios if s["id"] is not None] + reserved))
    next_free = (max(all_used) + 1) if all_used else 1

    out = {
        "_note": "GENERATED by authoring/scenario_inventory.py — do not hand-edit. Read this before "
                 "creating a scenario; take next_free_id for a new scenario's codec id.",
        "next_free_id": next_free,
        "ids_reserved_in_decoder": reserved,
        "duplicate_ids": dupes,
        "scenarios": sorted(scenarios, key=lambda s: (s["id"] is None, s["id"] or 0)),
    }
    OUT.write_text(json.dumps(out, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(scenarios)} scenarios, next_free_id={next_free}")
    if dupes:
        print("!! DUPLICATE ids:", dupes)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
